---
# HOST
target_hosts: localhost

# PROJECT DETAILS
repo_name: KubeflowCluster    # REPO DIR NAME
repo_path: /home/$USER/Git    # PATH OF REPO DIR ROOT 
owner_name: mg  
workspace_name: jenkins       #TERRAFORM WORKSPACE NAME

# CLUSTER CREATION
provisioner_type: scripts     # terraform OR scripts
provider_type: k3ai           # TERRAFORM: aws, gcp | SCRIPTS: k3ai, 
cluster_selector: kind        # DETERMINE CLUSTER TYPE: eks, ecs, gke, gcm, kind, k3s, k3ai

# CLUSTER DETAILS                              
cluster_name: kubeflow        # WHAT TO NAME THE NEW CLUSTER        
cluster_namespace: kubeflow   # NAMESPACE TO INSTALL APP INTO

# CLOUD PROVIDER DETAILS
aws_default_region: us-west-2 # DEFAULT AWS REGION
gcp_default_region: us-west1  # DEFAULT GCP REGION
gcp_project_id: kubeflow-kind # GCP PROJECT ID 

# REMOTE STATE
state_bucket: jenkins-state-nightwalkers
state_object_key: us-east-1/s3/jenkins-terraform.tfstate
lock_db: tf-state-jenkins-lock

# SECRETS
git_token:
become_root: false

